---
  - name: Include OS-specific variables.
    include_vars: "{{ ansible_os_family }}.yml"
    
  - name: configure repo on CentOS 
    block:
      - name: Install EPEL
        yum:
          name: http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
          state: installed

      - name: run yum-config-manager
        command: yum-config-manager --enable remi-php72

    when: ansible_distribution == 'CentOS'


  - name: add PHP Sury repo
    apt_repository:
      repo: ppa:ondrej/php
      state: present
    when: ansible_distribution == 'Ubuntu'

  - name: Install php
    package: name={{item}} state=present
    notify: reload apache
    with_items:
     "{{ php_extensions }}"
     
  - name: download composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer
    tags:
      - composer

  - name: install composer
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
    args:
      creates: /usr/local/bin/composer

  - name: rename composer.phar to composer
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    args:
      creates: /usr/local/bin/composer

  - name: make composer executable
    file:
      path: /usr/local/bin/composer
      mode: a+x
      state: file